import React, { useState, useEffect, useRef } from 'react';

const ForensicReports = () => {
    const [cases, setCases] = useState([]);
    const [selectedCase, setSelectedCase] = useState(null);
    const [expertNotes, setExpertNotes] = useState('');
    const [generating, setGenerating] = useState(false);
    const [report, setReport] = useState(null);
    const [error, setError] = useState(null);
    const [overrideScore, setOverrideScore] = useState(null);
    const reportRef = useRef(null);

    useEffect(() => {
        const fetchCases = async () => {
            try {
                const res = await fetch('/api/complaints');
                const data = await res.json();
                if (res.ok) setCases(data);
            } catch (e) { console.error(e); }
        };
        fetchCases();
    }, []);

    const handleCaseSelect = (e) => {
        const c = cases.find(x => x._id === e.target.value);
        setSelectedCase(c || null);
        
        // Pre-load the report if it was previously saved
        if (c && c.forensic_report) {
            setReport(c.forensic_report);
        } else {
            setReport(null);
        }
        
        setError(null);
        setOverrideScore(c ? ((parseFloat(c.ai_confidence_score) || 0) * 100).toFixed(0) : null);
    };

    const handleGenerate = async () => {
        if (!selectedCase) return;
        setGenerating(true);
        setReport(null);
        setError(null);
        try {
            const res = await fetch(`/api/complaints/${selectedCase._id}/report`, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ expertNotes, overrideScore })
            });
            const data = await res.json();
            if (!res.ok) throw new Error(data.error);
            setReport(data.report);
            // Scroll to report
            setTimeout(() => reportRef.current?.scrollIntoView({ behavior: 'smooth' }), 100);
        } catch (err) {
            setError(err.message);
        } finally {
            setGenerating(false);
        }
    };

    const handlePrint = () => {
        const printWindow = window.open('', '_blank');
        printWindow.document.write(`
            <html><head><title>Forensic Report - ${selectedCase?.caseRef || ''}</title>
            <style>
                body { font-family: 'Courier New', monospace; padding: 40px; line-height: 1.8; color: #1a202c; }
                h1 { color: #003366; border-bottom: 2px solid #003366; padding-bottom: 10px; }
                pre { white-space: pre-wrap; font-family: inherit; }
                .footer { margin-top: 40px; border-top: 1px solid #ccc; padding-top: 15px; font-size: 12px; color: #666; }
            </style></head>
            <body>
                <h1>🛡️ Cyber Nethra — Official Forensic Report</h1>
                <pre>${report}</pre>
                <div class="footer">Generated by Cyber Nethra AI Forensics System • ${new Date().toLocaleString()}</div>
            </body></html>`);
        printWindow.document.close();
        printWindow.print();
    };

    const ref = selectedCase;
    const getStatusColor = (s) => {
        if (s === 'AI-Flagged') return '#C53030';
        if (s === 'Resolved') return '#276749';
        return '#975A16';
    };

    return (
        <div style={st.container}>
            <div style={st.header}>
                <h2 style={st.heading}>📝 AI Forensic Report Generator</h2>
                <p style={st.sub}>Powered by Gemini AI — generates legally structured forensic reports from case data & evidence.</p>
            </div>

            <div style={st.layout}>
                {/* LEFT: Form Panel */}
                <div style={st.formCard}>
                    <h3 style={st.cardTitle}>⚙️ Report Configuration</h3>

                    {/* Case Selector */}
                    <div style={st.inputGroup}>
                        <label style={st.label}>Select Case File</label>
                        <select style={st.select} value={selectedCase?._id || ''} onChange={handleCaseSelect}>
                            <option value="">-- Select a Case --</option>
                            {cases.map(c => (
                                <option key={c._id} value={c._id}>
                                    {c.caseRef || `REF-${c._id.slice(-6).toUpperCase()}`} — {c.type} ({c.status})
                                </option>
                            ))}
                        </select>
                    </div>

                    {/* Case Snapshot */}
                    {selectedCase && (
                        <div style={st.snapshotBox}>
                            <div style={st.snapRow}>
                                <span style={st.snapLabel}>Case Ref:</span>
                                <strong style={{ fontFamily: 'monospace' }}>{selectedCase.caseRef || `REF-${selectedCase._id.slice(-6).toUpperCase()}`}</strong>
                            </div>
                            <div style={st.snapRow}>
                                <span style={st.snapLabel}>Type:</span>
                                <span>{selectedCase.type}</span>
                            </div>
                            <div style={st.snapRow}>
                                <span style={st.snapLabel}>Status:</span>
                                <span style={{ fontWeight: 'bold', color: getStatusColor(selectedCase.status) }}>{selectedCase.status}</span>
                            </div>
                            {selectedCase.ai_analysis_result && (
                                <div style={st.snapRow}>
                                    <span style={st.snapLabel}>AI Verdict:</span>
                                    <span style={{ fontWeight: 'bold', color: selectedCase.ai_analysis_result === 'Fake' ? '#C53030' : '#276749' }}>
                                        {selectedCase.ai_analysis_result === 'Fake' ? '⚠️ Deepfake' : '✅ Authentic'}
                                    </span>
                                </div>
                            )}
                            {selectedCase.evidence && (
                                <img
                                    src={`${import.meta.env.VITE_BACKEND_URL || ''}/${selectedCase.evidence.replace(/\\/g, '/')}`}
                                    alt="Evidence"
                                    style={st.thumbnail}
                                    onError={(e) => { e.target.style.display = 'none'; }}
                                />
                            )}
                        </div>
                    )}

                    {/* Override Score */}
                    {selectedCase && overrideScore !== null && (
                        <div style={st.inputGroup}>
                            <label style={st.label}>Override AI Confidence Score: <strong>{overrideScore}%</strong></label>
                            <input
                                type="range" min="0" max="100"
                                value={overrideScore}
                                onChange={e => setOverrideScore(e.target.value)}
                                style={{ width: '100%', accentColor: '#003366' }}
                            />
                            <small style={st.hint}>Expert may adjust the confidence score based on manual verification.</small>
                        </div>
                    )}

                    {/* Expert Notes */}
                    {selectedCase && (
                        <div style={st.inputGroup}>
                            <label style={st.label}>Expert Observations (Optional)</label>
                            <textarea
                                style={st.textarea}
                                rows={4}
                                placeholder="Add any additional observations, tools used, or manual findings for the AI to include..."
                                value={expertNotes}
                                onChange={e => setExpertNotes(e.target.value)}
                            />
                        </div>
                    )}

                    {/* Generate Button */}
                    <button
                        style={{ ...st.btn, opacity: (!selectedCase || generating) ? 0.6 : 1 }}
                        onClick={handleGenerate}
                        disabled={!selectedCase || generating}
                    >
                        {generating ? '🔄 Generating Report via Gemini AI...' : '🛡️ Generate Forensic Report'}
                    </button>

                    {error && (
                        <div style={st.errorBox}>
                            ❌ {error}
                        </div>
                    )}
                </div>

                {/* RIGHT: Report Preview */}
                <div style={st.reportPanel} ref={reportRef}>
                    <h3 style={st.cardTitle}>📄 Generated Report</h3>

                    {!report && !generating && (
                        <div style={st.placeholder}>
                            <p style={{ fontSize: '40px', margin: 0 }}>🔬</p>
                            <p>Select a case and click Generate to create an AI forensic report.</p>
                        </div>
                    )}

                    {generating && (
                        <div style={st.placeholder}>
                            <div style={st.spinner} />
                            <p style={{ color: '#2B6CB0', marginTop: '15px' }}>Gemini AI is analyzing the case data & evidence image...</p>
                        </div>
                    )}

                    {report && (
                        <div style={st.reportBody}>
                            <div style={st.reportToolbar}>
                                <span style={{ fontSize: '13px', color: '#718096' }}>
                                    Case: <strong>{selectedCase?.caseRef || ''}</strong> • {new Date().toLocaleString()}
                                </span>
                                <button style={st.printBtn} onClick={handlePrint}>🖨️ Print / Save PDF</button>
                            </div>
                            <pre style={st.reportText}>{report}</pre>
                        </div>
                    )}
                </div>
            </div>
        </div>
    );
};

const st = {
    container: { padding: '10px', height: '100%', display: 'flex', flexDirection: 'column', gap: '12px', overflowY: 'auto' },
    header: { paddingBottom: '10px', borderBottom: '1px solid #EDF2F7' },
    heading: { color: '#003366', margin: 0, fontSize: '22px' },
    sub: { color: '#718096', margin: '5px 0 0', fontSize: '14px' },
    layout: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(340px, 1fr))', gap: '20px', flex: 1, minHeight: 0 },

    formCard: { background: 'white', padding: '15px 20px', borderRadius: '12px', boxShadow: '0 4px 10px rgba(0,0,0,0.06)', display: 'flex', flexDirection: 'column', gap: '15px', overflowY: 'auto' },
    cardTitle: { color: '#2C5282', margin: '0 0 5px', fontSize: '16px', fontWeight: 'bold' },
    inputGroup: { display: 'flex', flexDirection: 'column', gap: '8px' },
    label: { fontWeight: 'bold', color: '#4A5568', fontSize: '13px' },
    select: { width: '100%', padding: '10px 12px', borderRadius: '8px', border: '1px solid #CBD5E0', fontSize: '14px', outline: 'none', cursor: 'pointer' },
    textarea: { width: '100%', padding: '10px', borderRadius: '8px', border: '1px solid #CBD5E0', fontFamily: 'inherit', fontSize: '14px', resize: 'vertical', outline: 'none', boxSizing: 'border-box' },
    hint: { color: '#A0AEC0', fontSize: '11px' },
    btn: { padding: '13px', background: '#003366', color: 'white', border: 'none', borderRadius: '8px', cursor: 'pointer', fontWeight: 'bold', fontSize: '15px', transition: 'opacity 0.2s' },
    errorBox: { background: '#FFF5F5', padding: '12px', borderRadius: '8px', color: '#C53030', border: '1px solid #FC8181', fontSize: '13px' },

    snapshotBox: { background: '#F7FAFC', padding: '15px', borderRadius: '10px', border: '1px solid #E2E8F0', display: 'flex', flexDirection: 'column', gap: '8px' },
    snapRow: { display: 'flex', gap: '10px', alignItems: 'center', fontSize: '14px' },
    snapLabel: { color: '#718096', minWidth: '80px', fontSize: '12px', textTransform: 'uppercase', letterSpacing: '0.5px' },
    thumbnail: { width: '100%', maxHeight: '140px', objectFit: 'cover', borderRadius: '8px', border: '1px solid #E2E8F0', marginTop: '5px' },

    reportPanel: { background: 'white', padding: '15px 20px', borderRadius: '12px', boxShadow: '0 4px 10px rgba(0,0,0,0.06)', display: 'flex', flexDirection: 'column', gap: '12px', overflowY: 'auto' },
    placeholder: { flex: 1, display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', color: '#A0AEC0', textAlign: 'center' },
    spinner: { width: '40px', height: '40px', border: '4px solid #EBF8FF', borderTop: '4px solid #3182CE', borderRadius: '50%', animation: 'spin 0.9s linear infinite', margin: '0 auto' },
    reportBody: { display: 'flex', flexDirection: 'column', gap: '15px' },
    reportToolbar: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '10px 15px', background: '#F7FAFC', borderRadius: '8px', border: '1px solid #EDF2F7' },
    printBtn: { padding: '6px 14px', background: '#2F855A', color: 'white', border: 'none', borderRadius: '6px', cursor: 'pointer', fontWeight: 'bold', fontSize: '12px' },
    reportText: { fontFamily: '"Courier New", monospace', fontSize: '13px', lineHeight: 1.8, color: '#2D3748', whiteSpace: 'pre-wrap', background: '#FAFCFF', padding: '20px', borderRadius: '8px', border: '1px solid #EDF2F7', margin: 0 },
};

// Inject spinner animation once
if (!document.getElementById('report-spinner-style')) {
    const style = document.createElement('style');
    style.id = 'report-spinner-style';
    style.textContent = '@keyframes spin { to { transform: rotate(360deg); } }';
    document.head.appendChild(style);
}

export default ForensicReports;
